// Code generated by ent, DO NOT EDIT.

package outbox

const (
	// Label holds the string label denoting the outbox type in the database.
	Label = "outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldConsumed holds the string denoting the consumed field in the database.
	FieldConsumed = "consumed"
	// Table holds the table name of the outbox in the database.
	Table = "outboxes"
)

// Columns holds all SQL columns for outbox fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldPayload,
	FieldConsumed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// KindValidator is a validator for the "kind" field. It is called by the builders before save.
	KindValidator func(string) error
)
