// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Outbox is the predicate function for outbox builders.
type Outbox func(*sql.Selector)

// Registration is the predicate function for registration builders.
type Registration func(*sql.Selector)
