// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/quintans/go-clean-ddd/internal/infra/gateway/postgres/ent/runtime.go

const (
	Version = "v0.10.2-0.20220615141015-7017cbc898e8"           // Version of ent codegen.
	Sum     = "h1:WiIPOXsYK+dySBSlDrPxNXwJNlYKHHI/xTY7UeCWtHw=" // Sum of ent codegen.
)
