// Code generated by gog; DO NOT EDIT.
// Version: 0.2.5
package vo

import (
	"github.com/pkg/errors"
)

// Generated by gog:record

func NewFullName(
	firstName string,
	lastName string,
) (FullName, error) {
	if firstName == "" {
		return FullName{}, errors.New("FullName.firstName cannot be empty")
	}
	if lastName == "" {
		return FullName{}, errors.New("FullName.lastName cannot be empty")
	}
	f := FullName{
		firstName: firstName,
		lastName:  lastName,
	}

	return f, nil
}

func MustNewFullName(
	firstName string,
	lastName string,
) FullName {
	f, err := NewFullName(
		firstName,
		lastName,
	)
	if err != nil {
		panic(err)
	}
	return f
}

func (f FullName) FirstName() string {
	return f.firstName
}

func (f FullName) LastName() string {
	return f.lastName
}

func (f FullName) IsZero() bool {
	return f == FullName{}
}

// Generated by gog:record

func NewEmail(
	email string,
) (Email, error) {
	if email == "" {
		return Email{}, errors.New("Email.email cannot be empty")
	}
	e := Email{
		email: email,
	}
	if err := e.validate(); err != nil {
		return Email{}, err
	}

	return e, nil
}

func MustNewEmail(
	email string,
) Email {
	e, err := NewEmail(
		email,
	)
	if err != nil {
		panic(err)
	}
	return e
}

func (e Email) Email() string {
	return e.email
}

func (e Email) IsZero() bool {
	return e == Email{}
}
