// Code generated by gog; DO NOT EDIT.
package model

// Generated by gog:value

func NewFullNameVO(firstName string, lastName string) FullNameVO {
	return FullNameVO{
		firstName: firstName,
		lastName:  lastName,
	}
}

func (t FullNameVO) FirstName() string {
	return t.firstName
}

func (t FullNameVO) WithFirstName(firstName string) FullNameVO {
	return FullNameVO{
		firstName: firstName,
		lastName:  t.lastName,
	}
}

func (t FullNameVO) LastName() string {
	return t.lastName
}

func (t FullNameVO) WithLastName(lastName string) FullNameVO {
	return FullNameVO{
		firstName: t.firstName,
		lastName:  lastName,
	}
}
