// Code generated by ent, DO NOT EDIT.

package registration

const (
	// Label holds the string label denoting the registration type in the database.
	Label = "registration"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldVerified holds the string denoting the verified field in the database.
	FieldVerified = "verified"
	// Table holds the table name of the registration in the database.
	Table = "registrations"
)

// Columns holds all SQL columns for registration fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldVerified,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
