// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quintans/go-clean-ddd/internal/infra/gateway/postgres/ent/registration"
)

// RegistrationCreate is the builder for creating a Registration entity.
type RegistrationCreate struct {
	config
	mutation *RegistrationMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (rc *RegistrationCreate) SetEmail(s string) *RegistrationCreate {
	rc.mutation.SetEmail(s)
	return rc
}

// SetVerified sets the "verified" field.
func (rc *RegistrationCreate) SetVerified(b bool) *RegistrationCreate {
	rc.mutation.SetVerified(b)
	return rc
}

// SetID sets the "id" field.
func (rc *RegistrationCreate) SetID(s string) *RegistrationCreate {
	rc.mutation.SetID(s)
	return rc
}

// Mutation returns the RegistrationMutation object of the builder.
func (rc *RegistrationCreate) Mutation() *RegistrationMutation {
	return rc.mutation
}

// Save creates the Registration in the database.
func (rc *RegistrationCreate) Save(ctx context.Context) (*Registration, error) {
	var (
		err  error
		node *Registration
	)
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RegistrationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Registration)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RegistrationMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RegistrationCreate) SaveX(ctx context.Context) *Registration {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RegistrationCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RegistrationCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RegistrationCreate) check() error {
	if _, ok := rc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Registration.email"`)}
	}
	if _, ok := rc.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "Registration.verified"`)}
	}
	return nil
}

func (rc *RegistrationCreate) sqlSave(ctx context.Context) (*Registration, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Registration.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (rc *RegistrationCreate) createSpec() (*Registration, *sqlgraph.CreateSpec) {
	var (
		_node = &Registration{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: registration.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: registration.FieldID,
			},
		}
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: registration.FieldEmail,
		})
		_node.Email = value
	}
	if value, ok := rc.mutation.Verified(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: registration.FieldVerified,
		})
		_node.Verified = value
	}
	return _node, _spec
}

// RegistrationCreateBulk is the builder for creating many Registration entities in bulk.
type RegistrationCreateBulk struct {
	config
	builders []*RegistrationCreate
}

// Save creates the Registration entities in the database.
func (rcb *RegistrationCreateBulk) Save(ctx context.Context) ([]*Registration, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Registration, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RegistrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RegistrationCreateBulk) SaveX(ctx context.Context) []*Registration {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RegistrationCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RegistrationCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
