// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/quintans/go-clean-ddd/internal/infra/gateway/postgres/ent/customer"
	"github.com/quintans/go-clean-ddd/internal/infra/gateway/postgres/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescFirstName is the schema descriptor for first_name field.
	customerDescFirstName := customerFields[2].Descriptor()
	// customer.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	customer.FirstNameValidator = customerDescFirstName.Validators[0].(func(string) error)
	// customerDescLastName is the schema descriptor for last_name field.
	customerDescLastName := customerFields[3].Descriptor()
	// customer.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	customer.LastNameValidator = customerDescLastName.Validators[0].(func(string) error)
	// customerDescEmail is the schema descriptor for email field.
	customerDescEmail := customerFields[4].Descriptor()
	// customer.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	customer.EmailValidator = customerDescEmail.Validators[0].(func(string) error)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.IDValidator is a validator for the "id" field. It is called by the builders before save.
	customer.IDValidator = customerDescID.Validators[0].(func(string) error)
}
